extrair_perfil:
  description: >
    Criar um perfil de um estudante com base no histórico acadêmico dele.
  expected_output: >
    Uma lista de disciplinas já cursadas e um report conciso com o perfil dele em computação (incluindo áreas de interesse e áreas de dificuldade)
  agent: analista

recomendar_disciplinas:
  description: >
    Analisar o perfil do estudante e, com base no fluxograma do curso e nas disciplinas ofertadas atualmente
    definir disciplinas em que ele deve se matricular.
    Para selecionar optativas, verifique as disciplinas optativas em sua base de conhecimento.
    Não selecionar disciplinas (obrigatórias ou optativas) que o aluno já foi aprovado ou que está matriculado atualmente.
    A matrícula deve ser em no mínimo 4 disciplinas e no máximo 7.
  expected_output: >
    Uma lista das disciplinas que o estudante deve cursar esse período em bullets e, ao final de tudo, uma curta explicação das decisões.
  agent: recomendador

